messages:
  teleport_initiated: "&6Teleportation will commence in &c3 &6seconds. Don't move."
  teleporting: "&6Teleportation commencing..."
  aborted: "&cTeleportation aborted because you moved."
  location_blocked: "&cTeleportation blocked to this location - restricted"
  tp_admin_bypass: "Administrative Bypass of Region Teleport blocking used"
  unsafe_location: "&cUnable to find a safe location for teleport."
  tptop: "&6Teleporting to top."
  invalid_or_offline_player: "&cInvalid username or player is offline: "
  relative_coords_not_valid: "&cRelative coords not valid due to world or server switch"
  invalid_x_coordinate_or_player: "&cInvalid X coordinate (or unknown player): "
  invalid: "&cInvalid "
  coordinate: " coordinate: "
  no_longer_online: "Player is no longer online"
  no_perms_for_teleporting_others: "&cYou do not have permission to teleport others"
  sending: "&6Sending "
  to: " to "
  in_world: " in world "
  on_server: " on server "
  invalid_yaw: "&cInvalid yaw: "
  invalid_pitch: "&cInvalid pitch: "
teleport:
  denyon:
    cmdlist: "/noentry"
options:
  debug_logging: false
~
